module CodeNode

open System
open Bolero
open Bolero.Html
open Hywe.Core.Parse
open NodeCode

// Match syntax generated by the graph input
let preprocessCode (code: string) : string =
    let levels = splitIntoLevels code
    
    let processedLevels = 
        levels |> Array.map (fun levelData ->
            let marker = levelData.Marker
            let blocks = levelData.Blocks
            
            match Array.toList blocks with
            | [] -> ""
            | attrBlock :: nodeBlocks ->
                let lines = nodeBlocks |> List.toArray

                let topLevelInts =
                    lines
                    |> Array.choose (fun line ->
                        let parts = line.Split('/')
                        match parts.Length >= 3 with
                        | true ->
                            let path = parts.[0]
                            let firstSeg = path.Split('.').[0]
                            match Int32.TryParse firstSeg with
                            | true, n when n > 1 -> Some n
                            | _ -> None
                        | false -> None
                    )
                    |> Set.ofArray

                let intMap =
                    topLevelInts
                    |> Seq.map (fun n -> 
                        let mapped = String.Join(".", Array.create (n - 1) "0")
                        (n.ToString(), match mapped = "" with true -> "1" | false -> "1." + mapped))
                    |> dict

                let updatedLines =
                    lines
                    |> Array.map (fun line ->
                        let parts = line.Split('/')
                        match parts.Length >= 3 with
                        | true ->
                            let path = parts.[0]
                            let segments = path.Split('.')
                            let first = segments.[0]
                            let extra = match parts.Length > 3 with true -> "/" + parts.[3] | false -> ""
                            match intMap.ContainsKey(first) with
                            | true ->
                                let newPath = 
                                    match segments.Length > 1 with
                                    | true -> String.Join(".", Array.append [| intMap.[first] |] segments.[1..])
                                    | false -> intMap.[first]
                                $"({newPath}/{parts.[1]}/{parts.[2]}{extra})"
                            | false -> $"({line})"
                        | false -> $"({line})"
                    )

                let result = String.Join("", updatedLines)
                $"{marker}({attrBlock}){result}"
        )

    String.Join("", processedLevels)

// Parses the processed input into a tree structure for each level
let parseOutput (code: string) : TreeNode list =
    let levels = splitIntoLevels code
    
    levels |> Array.toList |> List.mapi (fun lvlIdx levelData ->
        let entries =
            levelData.Blocks 
            |> Array.skip 1 // skip attrs
            |> Array.choose (fun item ->
                let parts = item.Split('/')
                match parts.Length >= 3 with
                | true ->
                    let path = parts.[0]
                    match path.StartsWith("0") with
                    | true -> None
                    | false ->
                        let weight = parts.[1]
                        let name = parts.[2]
                        let extrusion = 
                            match parts.Length > 3 with 
                            | true -> match parts.[3] with Float v -> v | _ -> 3.0 
                            | false -> 3.0
                        Some (path, weight, name, extrusion)
                | false -> None
            )

        match entries |> Array.exists (fun (path, _, _, _) -> path = "1") with
        | false ->
            {
                Id = Guid.NewGuid()
                Name = sprintf "Level %d (No Root)" lvlIdx
                Weight = "0"
                X = 0.0
                Y = 0.0
                Children = []
                Level = lvlIdx
                Extrusion = 3.0
            }
        | true ->
            let nodeMap =
                entries
                |> Seq.map (fun (path, weight, name, extrusion) ->
                    path, {
                        Id = Guid.NewGuid()
                        Name = name
                        Weight = weight
                        X = 0.0
                        Y = 0.0
                        Children = []
                        Level = lvlIdx
                        Extrusion = extrusion
                    }
                )
                |> dict
                |> System.Collections.Generic.Dictionary

            let byDepth =
                entries
                |> Array.groupBy (fun (path, _, _, _) -> path.Split('.').Length)
                |> Array.sortByDescending fst

            for (_, group) in byDepth do
                for (path, _, _, _) in group do
                    match path.Contains '.' with
                    | true ->
                        let parentPath = path.Substring(0, path.LastIndexOf('.'))
                        match nodeMap.ContainsKey(parentPath) && nodeMap.ContainsKey(path) with
                        | true ->
                            let parent = nodeMap.[parentPath]
                            let child = nodeMap.[path]
                            nodeMap.[parentPath] <- { parent with Children = parent.Children @ [child] }
                        | false -> ()
                    | false -> ()

            nodeMap.["1"]
    )

let computeCanvasBounds (nodes: TreeNode list) : float * float =
    let margin = 50.0
    let maxX = nodes |> List.map (fun n -> n.X) |> List.max
    let maxY = nodes |> List.map (fun n -> n.Y) |> List.max
    maxX + margin, maxY + margin

let rec flattenTree (node: TreeNode) : TreeNode list =
    node :: (node.Children |> List.collect flattenTree)

let rec layoutTree (node: TreeNode) (depth: int) (xRef: float ref) : TreeNode =
    let horizontalSpacing = 80.0
    let verticalSpacing = 55.0

    let laidOutChildren =
        node.Children
        |> List.map (fun child -> layoutTree child (depth + 1) xRef)

    let x =
        if laidOutChildren.IsEmpty then
            let x = xRef.Value
            xRef.Value <- x + horizontalSpacing
            x
        else
            laidOutChildren |> List.averageBy (fun n -> n.X)

    {
        node with
            X = x
            Y = float depth * verticalSpacing
            Children = laidOutChildren
    }

type svLin = Template<""" <line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${st}" />""">
type svRct = Template<""" <rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" ry="${ry}" fill="${fl}" stroke="${st}" />""">
type svTxt = Template<""" <text x="${x}" y="${y}" font-size="${sz}" text-anchor="${ta}" fill="${fl}">${nm}</text>""">

let viewTreeSvg (root: TreeNode) : Node =
    let root = layoutTree root 0 (ref 100.0)
    let nodes = flattenTree root

    let margin = 50.0
    let minX = nodes |> List.map (fun n -> n.X) |> List.min
    let maxX = nodes |> List.map (fun n -> n.X) |> List.max
    let minY = nodes |> List.map (fun n -> n.Y) |> List.min
    let maxY = nodes |> List.map (fun n -> n.Y) |> List.max

    let vbX = minX - margin
    let vbY = minY - margin
    let vbW = maxX - minX + 2.0 * margin
    let vbH = maxY - minY + 2.0 * margin
    let viewBoxStr = sprintf "%f %f %f %f" vbX vbY vbW vbH

    let rec renderConnections (parent: TreeNode) : Node list =
        parent.Children
        |> List.collect (fun child ->
            [
                svLin()
                    .x1(string parent.X)
                    .y1(string parent.Y)
                    .x2(string child.X)
                    .y2(string child.Y)
                    .st("#cccccc")
                    .Elt()
            ] @ renderConnections child
        )

    let renderNode (node: TreeNode) : Node list =
        [
            svRct()
                .x(string (node.X - 30.0))
                .y(string (node.Y - 20.0))
                .w("60")
                .h("30")
                .rx("6")
                .ry("6")
                .fl("white")
                .st("#aaaaaa")
                .Elt()

            svTxt()
                .x(string node.X)
                .y(string (node.Y - 6.5))
                .ta("middle")
                .sz("11")
                .fl("#333333")
                .nm(node.Name)
                .Elt()

            svTxt()
                .x(string node.X)
                .y(string (node.Y + 4.5))
                .ta("middle")
                .sz("10")
                .fl("#777777")
                .nm(node.Weight)
                .Elt()
        ]

    svg {
        yield attr.width "100%"
        yield attr.height "100%"
        yield "viewBox" => viewBoxStr
        yield attr.style "max-width: 100%; height: auto; display: block; margin: auto;"

        for conn in renderConnections root do
            yield conn

        for node in nodes do
            for el in renderNode node do
                yield el
    }

let viewCodeGraphFromString (code: string) : Node =
    try
        let processed = preprocessCode code
        let roots = parseOutput processed
        
        div {
            attr.style "margin-top: 20px; font-family: monospace; font-size: 14px; color: #444;"
            forEach (roots |> List.indexed) <| fun (i, root) ->
                div {
                    attr.style "margin-bottom: 30px; border-bottom: 1px solid #eee; padding-bottom: 10px;"
                    div {
                        attr.style "font-weight: bold; color: #888; text-transform: uppercase; margin-bottom: 5px; font-size: 12px;"
                        text (sprintf "Architecture Level %d" i)
                    }
                    viewTreeSvg root
                }
            $"Processed code: {processed}"
        }
    with ex ->
        div {
            attr.style "color:red"
            text $"Error: {ex.Message}"
        }
