name: DeployToGitHubPages
env:
  PUBLISH_DIR: bin/Release/net8.0/publish/wwwroot

on:
  push:
    branches: [master]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - run: dotnet publish -c Release

      - run: echo 'hywe.in' > ${{ env.PUBLISH_DIR }}/CNAME

      - uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v2
