name: DeployToGitHubPages
env:
  PUBLISH_DIR: bin/Release/net6.0/publish/wwwroot

# Controls when the action will run
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Publish app
      run: dotnet publish -c Release

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1.1.0
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /Hywe/

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
